[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat/=node_modules/hardhat/',
]
ffi=true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config